In [1]:
import numpy as np

In [2]:
age_list = [22, 38, 26, 35, 35, 27, 54, 2, 27, 14]
age_array = np.array(age_list)
print(type(age_array))  # Output: <class 'numpy.ndarray'>
print(age_array)  # Output: [22 38 26 35 35 27 54 2 27 14]

<class 'numpy.ndarray'>
[22 38 26 35 35 27 54  2 27 14]


In [3]:
# ndarray properties
print('Shape: ', age_array.shape)  # Output: (10,) 
print('Dimensions: ', age_array.ndim)  # Output: 1
print('Size: ', age_array.size)  # Output: 10
print('Data type: ', age_array.dtype)  # Output: int64 (or int32 depending on the system)

Shape:  (10,)
Dimensions:  1
Size:  10
Data type:  int64


In [4]:
a = np.zeros(5)
b = np.ones(5)
c = np.arange(0, 20, 2)
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 0  2  4  6  8 10 12 14 16 18]


In [13]:
# matrix = np.array([[[[1, 2], [3, 4]], 
#                    [[5, 6], [7, 8]], 
#                    [[9, 10], [11, 12]]],
#                    [[[1, 2], [3, 4]], 
#                    [[5, 6], [7, 8]], 
#                    [[9, 10], [11, 12]]]])
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
matrix.ndim

2

In [15]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [17]:
matrix = a.reshape(3, 4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
print(matrix[1, 2])

6
